openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - cluster_name
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: Name of the Kubernetes cluster
          x-walrus-ui:
            group: Basic
            order: 1
        cluster_mesh_enabled:
          title: Cluster Mesh Enabled
          type: boolean
          description: Enable or disable cluster mesh
          default: true
          x-walrus-ui:
            group: Basic
            order: 2
        cluster_id:
          title: Cluster Id
          type: number
          description: ID of the Kubernetes cluster, must be different for ClusterMesh
          default: 1
          x-walrus-ui:
            group: Basic
            order: 3
        version:
          title: Version
          type: string
          description: Version of the Cilium chart
          default: 1.16.1
          x-walrus-ui:
            group: Basic
            order: 4
        hubble_enabled:
          title: Hubble Enabled
          type: boolean
          description: Enable or disable Hubble relay and UI
          default: true
          x-walrus-ui:
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
