openapi: 3.0.3
info:
  title: OpenAPI schema for Cilium template .
components:
  schemas:
    variables:
      type: object
      required:
      - cluster_name
      properties:
        cluster_name:
          title: Cluster Name
          type: string
          description: Name of the Kubernetes cluster
          x-walrus-ui:
            group: Basic
            order: 1
        cluster_ui_enabled:
          title: Cluster Ui Enabled
          type: boolean
          description: Enable or disable hubble UI
          default: true
          x-walrus-ui:
            group: Basic
            order: 2
        cluster_id:
          title: Cluster Id
          type: number
          description: ID of the Kubernetes cluster, must be different for ClusterMesh
          default: 1
          x-walrus-ui:
            group: Basic
            order: 3
        helm_release_version:
          title: Helm Release Version
          type: string
          description: Version of the Cilium chart
          default: 1.16.2
          x-walrus-ui:
            group: Basic
            order: 4
        hubble_enabled:
          title: Hubble Enabled
          type: boolean
          description: Enable or disable Hubble relay and UI
          default: true
          x-walrus-ui:
            group: Basic
            order: 5
        kube_proxy_replacement:
          title: Kube Proxy Replacement
          type: boolean
          description: Enable or disable KubeProxyReplacement.
          default: true
          x-walrus-ui:
            group: Basic
            order: 6
        ipv4_pod_cidrlist:
          title: Ipv4 Pod Cidrlist
          type: string
          description: Cluster Pool IPv4 CIDR list
          default: 10.0.0.0/16
          x-walrus-ui:
            group: Basic
            order: 7
        ipv4_native_routing_cidr:
          title: Ipv4 Native Routing Cidr
          type: string
          description: IPv4 native routing CIDR
          default: 10.0.0.0/8
          x-walrus-ui:
            group: Basic
            order: 8
        clustermesh_max:
          title: Clustermesh Max
          type: string
          description: Cluster Mesh max cluster connected
          default: "511"
          x-walrus-ui:
            group: Basic
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
